//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Folders()
        {
            this.Folders1 = new HashSet<Folders>();
            this.Images = new HashSet<Images>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] MetaDataPicture { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentFolder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Folders> Folders1 { get; set; }
        public virtual Folders Folders2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
    }
}
